name: Build & Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: AWS IAM 사용자 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 의존성 설치
        run: yarn install

      - name: 리액트 빌드
        run: yarn build
        env:
          VITE_APP_BASE_URL: ${{ secrets.VITE_APP_BASE_URL }}
          VITE_KAKAO_CLIENT_TO_ID: ${{ secrets.VITE_KAKAO_CLIENT_TO_ID }}
          VITE_APP_KAKAO_REDIRECT_URI: ${{ secrets.VITE_APP_KAKAO_REDIRECT_URI }}
          VITE_APP_WS_URL: ${{ secrets.VITE_APP_WS_URL }}

      - name: 빌드한 파일 S3에 업로드
        run: aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}

      - name: CloudFront 캐시 무력화 설정
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_ID }}
          PATHS: "/*"
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
